package com.hsjc.central.mapper;

import com.hsjc.central.domain.Restactiontype;

public interface RestactiontypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestactiontype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestactiontype
     *
     * @mbggenerated
     */
    int insert(Restactiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestactiontype
     *
     * @mbggenerated
     */
    int insertSelective(Restactiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestactiontype
     *
     * @mbggenerated
     */
    Restactiontype selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestactiontype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Restactiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestactiontype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Restactiontype record);
}