package com.hsjc.central.mapper;

import com.hsjc.central.domain.RestfulLog;

public interface RestfulLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestfullog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long restlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestfullog
     *
     * @mbggenerated
     */
    int insert(RestfulLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestfullog
     *
     * @mbggenerated
     */
    int insertSelective(RestfulLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestfullog
     *
     * @mbggenerated
     */
    RestfulLog selectByPrimaryKey(Long restlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestfullog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RestfulLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrestfullog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RestfulLog record);
}