package com.hsjc.central.mapper;

import com.hsjc.central.domain.SchoolInvite;

public interface SchoolInviteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbschoolinvite
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long inviteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbschoolinvite
     *
     * @mbggenerated
     */
    int insert(SchoolInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbschoolinvite
     *
     * @mbggenerated
     */
    int insertSelective(SchoolInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbschoolinvite
     *
     * @mbggenerated
     */
    SchoolInvite selectByPrimaryKey(Long inviteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbschoolinvite
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolInvite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbschoolinvite
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolInvite record);
}