package com.hsjc.central.mapper;

import com.hsjc.central.domain.SsoClientDetails;

public interface SsoClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssoclientdetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssoclientdetails
     *
     * @mbggenerated
     */
    int insert(SsoClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssoclientdetails
     *
     * @mbggenerated
     */
    int insertSelective(SsoClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssoclientdetails
     *
     * @mbggenerated
     */
    SsoClientDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssoclientdetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SsoClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssoclientdetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SsoClientDetails record);
}