package com.hsjc.central.mapper;

import com.hsjc.central.domain.SystemLog;

public interface SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsystemlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long syslogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsystemlog
     *
     * @mbggenerated
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsystemlog
     *
     * @mbggenerated
     */
    int insertSelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsystemlog
     *
     * @mbggenerated
     */
    SystemLog selectByPrimaryKey(Long syslogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsystemlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsystemlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemLog record);
}