package com.hsjc.central.mapper;

import com.hsjc.central.domain.TbEmailResetPwd;

public interface TbEmailResetPwdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailresetpwd
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailresetpwd
     *
     * @mbggenerated
     */
    int insert(TbEmailResetPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailresetpwd
     *
     * @mbggenerated
     */
    int insertSelective(TbEmailResetPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailresetpwd
     *
     * @mbggenerated
     */
    TbEmailResetPwd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailresetpwd
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbEmailResetPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailresetpwd
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbEmailResetPwd record);
}