package com.hsjc.central.mapper;

import com.hsjc.central.domain.TbEmailSend;

public interface TbEmailSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    int insert(TbEmailSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    int insertSelective(TbEmailSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    TbEmailSend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbEmailSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbEmailSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbemailsend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbEmailSend record);
}