package com.hsjc.central.mapper;

import com.hsjc.central.domain.TbSmsSend;

public interface TbSmsSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmssend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmssend
     *
     * @mbggenerated
     */
    int insert(TbSmsSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmssend
     *
     * @mbggenerated
     */
    int insertSelective(TbSmsSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmssend
     *
     * @mbggenerated
     */
    TbSmsSend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmssend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbSmsSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmssend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSmsSend record);
}