package com.hsjc.central.mapper;

import com.hsjc.central.domain.TbSmsResetPasswd;

public interface TbSmsResetPasswdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsresetpasswd
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer resetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsresetpasswd
     *
     * @mbggenerated
     */
    int insert(TbSmsResetPasswd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsresetpasswd
     *
     * @mbggenerated
     */
    int insertSelective(TbSmsResetPasswd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsresetpasswd
     *
     * @mbggenerated
     */
    TbSmsResetPasswd selectByPrimaryKey(Integer resetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsresetpasswd
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbSmsResetPasswd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsresetpasswd
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSmsResetPasswd record);
}