package com.hsjc.central.mapper;

import com.hsjc.central.domain.TbSmsBindPhoneNum;

public interface TbSmsBindPhoneNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsbindphonenum
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bindid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsbindphonenum
     *
     * @mbggenerated
     */
    int insert(TbSmsBindPhoneNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsbindphonenum
     *
     * @mbggenerated
     */
    int insertSelective(TbSmsBindPhoneNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsbindphonenum
     *
     * @mbggenerated
     */
    TbSmsBindPhoneNum selectByPrimaryKey(Integer bindid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsbindphonenum
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbSmsBindPhoneNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsmsbindphonenum
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSmsBindPhoneNum record);
}