package com.hsjc.central.mapper;

import com.hsjc.central.domain.UserStudent;

public interface UserStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstudent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstudent
     *
     * @mbggenerated
     */
    int insert(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstudent
     *
     * @mbggenerated
     */
    int insertSelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstudent
     *
     * @mbggenerated
     */
    UserStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstudent
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userstudent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserStudent record);
}