package com.hsjc.central.mapper;

import com.hsjc.central.domain.UserMain;
import org.apache.ibatis.annotations.Param;

public interface UserMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermain
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermain
     *
     * @mbggenerated
     */
    int insert(UserMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermain
     *
     * @mbggenerated
     */
    int insertSelective(UserMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermain
     *
     * @mbggenerated
     */
    UserMain selectByPrimaryKey(Integer id);

    UserMain selectByUserName(@Param("userName") String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermain
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserMain record);
}