package com.hsjc.central.domain;

import java.util.Date;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.organizationid
     *
     * @mbggenerated
     */
    private Integer organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.organizationname
     *
     * @mbggenerated
     */
    private String organizationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.parentid
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborganization.isdelete
     *
     * @mbggenerated
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.id
     *
     * @return the value of tborganization.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.id
     *
     * @param id the value for tborganization.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.organizationid
     *
     * @return the value of tborganization.organizationid
     *
     * @mbggenerated
     */
    public Integer getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.organizationid
     *
     * @param organizationid the value for tborganization.organizationid
     *
     * @mbggenerated
     */
    public void setOrganizationid(Integer organizationid) {
        this.organizationid = organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.organizationname
     *
     * @return the value of tborganization.organizationname
     *
     * @mbggenerated
     */
    public String getOrganizationname() {
        return organizationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.organizationname
     *
     * @param organizationname the value for tborganization.organizationname
     *
     * @mbggenerated
     */
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname == null ? null : organizationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.parentid
     *
     * @return the value of tborganization.parentid
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.parentid
     *
     * @param parentid the value for tborganization.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.status
     *
     * @return the value of tborganization.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.status
     *
     * @param status the value for tborganization.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.createtime
     *
     * @return the value of tborganization.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.createtime
     *
     * @param createtime the value for tborganization.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborganization.isdelete
     *
     * @return the value of tborganization.isdelete
     *
     * @mbggenerated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborganization.isdelete
     *
     * @param isdelete the value for tborganization.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}