package com.hsjc.central.domain;

import java.util.Date;

public class RestfulLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestfullog.restlogid
     *
     * @mbggenerated
     */
    private Long restlogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestfullog.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestfullog.actionid
     *
     * @mbggenerated
     */
    private Integer actionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestfullog.respcode
     *
     * @mbggenerated
     */
    private Integer respcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestfullog.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestfullog.actiontime
     *
     * @mbggenerated
     */
    private Date actiontime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestfullog.restlogid
     *
     * @return the value of tbrestfullog.restlogid
     *
     * @mbggenerated
     */
    public Long getRestlogid() {
        return restlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestfullog.restlogid
     *
     * @param restlogid the value for tbrestfullog.restlogid
     *
     * @mbggenerated
     */
    public void setRestlogid(Long restlogid) {
        this.restlogid = restlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestfullog.userid
     *
     * @return the value of tbrestfullog.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestfullog.userid
     *
     * @param userid the value for tbrestfullog.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestfullog.actionid
     *
     * @return the value of tbrestfullog.actionid
     *
     * @mbggenerated
     */
    public Integer getActionid() {
        return actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestfullog.actionid
     *
     * @param actionid the value for tbrestfullog.actionid
     *
     * @mbggenerated
     */
    public void setActionid(Integer actionid) {
        this.actionid = actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestfullog.respcode
     *
     * @return the value of tbrestfullog.respcode
     *
     * @mbggenerated
     */
    public Integer getRespcode() {
        return respcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestfullog.respcode
     *
     * @param respcode the value for tbrestfullog.respcode
     *
     * @mbggenerated
     */
    public void setRespcode(Integer respcode) {
        this.respcode = respcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestfullog.description
     *
     * @return the value of tbrestfullog.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestfullog.description
     *
     * @param description the value for tbrestfullog.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestfullog.actiontime
     *
     * @return the value of tbrestfullog.actiontime
     *
     * @mbggenerated
     */
    public Date getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestfullog.actiontime
     *
     * @param actiontime the value for tbrestfullog.actiontime
     *
     * @mbggenerated
     */
    public void setActiontime(Date actiontime) {
        this.actiontime = actiontime;
    }
}