package com.hsjc.central.domain;

public class Restactiontype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestactiontype.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestactiontype.actionid
     *
     * @mbggenerated
     */
    private Integer actionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestactiontype.actionname
     *
     * @mbggenerated
     */
    private String actionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrestactiontype.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestactiontype.id
     *
     * @return the value of tbrestactiontype.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestactiontype.id
     *
     * @param id the value for tbrestactiontype.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestactiontype.actionid
     *
     * @return the value of tbrestactiontype.actionid
     *
     * @mbggenerated
     */
    public Integer getActionid() {
        return actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestactiontype.actionid
     *
     * @param actionid the value for tbrestactiontype.actionid
     *
     * @mbggenerated
     */
    public void setActionid(Integer actionid) {
        this.actionid = actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestactiontype.actionname
     *
     * @return the value of tbrestactiontype.actionname
     *
     * @mbggenerated
     */
    public String getActionname() {
        return actionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestactiontype.actionname
     *
     * @param actionname the value for tbrestactiontype.actionname
     *
     * @mbggenerated
     */
    public void setActionname(String actionname) {
        this.actionname = actionname == null ? null : actionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrestactiontype.description
     *
     * @return the value of tbrestactiontype.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrestactiontype.description
     *
     * @param description the value for tbrestactiontype.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}