package com.hsjc.central.domain;

import java.util.Date;

public class SchoolInvite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.inviteid
     *
     * @mbggenerated
     */
    private Long inviteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.invitecode
     *
     * @mbggenerated
     */
    private String invitecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.schoolid
     *
     * @mbggenerated
     */
    private Integer schoolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.byuserid
     *
     * @mbggenerated
     */
    private Long byuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbschoolinvite.usetime
     *
     * @mbggenerated
     */
    private Date usetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.inviteid
     *
     * @return the value of tbschoolinvite.inviteid
     *
     * @mbggenerated
     */
    public Long getInviteid() {
        return inviteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.inviteid
     *
     * @param inviteid the value for tbschoolinvite.inviteid
     *
     * @mbggenerated
     */
    public void setInviteid(Long inviteid) {
        this.inviteid = inviteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.invitecode
     *
     * @return the value of tbschoolinvite.invitecode
     *
     * @mbggenerated
     */
    public String getInvitecode() {
        return invitecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.invitecode
     *
     * @param invitecode the value for tbschoolinvite.invitecode
     *
     * @mbggenerated
     */
    public void setInvitecode(String invitecode) {
        this.invitecode = invitecode == null ? null : invitecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.schoolid
     *
     * @return the value of tbschoolinvite.schoolid
     *
     * @mbggenerated
     */
    public Integer getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.schoolid
     *
     * @param schoolid the value for tbschoolinvite.schoolid
     *
     * @mbggenerated
     */
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.byuserid
     *
     * @return the value of tbschoolinvite.byuserid
     *
     * @mbggenerated
     */
    public Long getByuserid() {
        return byuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.byuserid
     *
     * @param byuserid the value for tbschoolinvite.byuserid
     *
     * @mbggenerated
     */
    public void setByuserid(Long byuserid) {
        this.byuserid = byuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.state
     *
     * @return the value of tbschoolinvite.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.state
     *
     * @param state the value for tbschoolinvite.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.createtime
     *
     * @return the value of tbschoolinvite.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.createtime
     *
     * @param createtime the value for tbschoolinvite.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbschoolinvite.usetime
     *
     * @return the value of tbschoolinvite.usetime
     *
     * @mbggenerated
     */
    public Date getUsetime() {
        return usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbschoolinvite.usetime
     *
     * @param usetime the value for tbschoolinvite.usetime
     *
     * @mbggenerated
     */
    public void setUsetime(Date usetime) {
        this.usetime = usetime;
    }
}