package com.hsjc.central.domain;

import java.io.Serializable;

/**
 * @author : zga
 * @date : 2015-12-2
 */
public class SmsBindPhoneNum implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmsbindphonenum.BindID
     *
     * @mbggenerated
     */
    private Integer bindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmsbindphonenum.AuthID
     *
     * @mbggenerated
     */
    private Integer authid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmsbindphonenum.UserID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmsbindphonenum.BindID
     *
     * @return the value of tbsmsbindphonenum.BindID
     *
     * @mbggenerated
     */
    public Integer getBindid() {
        return bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmsbindphonenum.BindID
     *
     * @param bindid the value for tbsmsbindphonenum.BindID
     *
     * @mbggenerated
     */
    public void setBindid(Integer bindid) {
        this.bindid = bindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmsbindphonenum.AuthID
     *
     * @return the value of tbsmsbindphonenum.AuthID
     *
     * @mbggenerated
     */
    public Integer getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmsbindphonenum.AuthID
     *
     * @param authid the value for tbsmsbindphonenum.AuthID
     *
     * @mbggenerated
     */
    public void setAuthid(Integer authid) {
        this.authid = authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmsbindphonenum.UserID
     *
     * @return the value of tbsmsbindphonenum.UserID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmsbindphonenum.UserID
     *
     * @param userid the value for tbsmsbindphonenum.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}