package com.hsjc.central.domain;

import java.io.Serializable;

public class SsoClientDetails implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssoclientdetails.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssoclientdetails.client_id
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssoclientdetails.client_secret
     *
     * @mbggenerated
     */
    private String clientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssoclientdetails.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssoclientdetails.id
     *
     * @return the value of ssoclientdetails.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssoclientdetails.id
     *
     * @param id the value for ssoclientdetails.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssoclientdetails.client_id
     *
     * @return the value of ssoclientdetails.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssoclientdetails.client_id
     *
     * @param clientId the value for ssoclientdetails.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssoclientdetails.client_secret
     *
     * @return the value of ssoclientdetails.client_secret
     *
     * @mbggenerated
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssoclientdetails.client_secret
     *
     * @param clientSecret the value for ssoclientdetails.client_secret
     *
     * @mbggenerated
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssoclientdetails.userId
     *
     * @return the value of ssoclientdetails.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssoclientdetails.userId
     *
     * @param userid the value for ssoclientdetails.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}