package com.hsjc.central.domain;

import java.util.Date;

public class SystemLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsystemlog.syslogid
     *
     * @mbggenerated
     */
    private Long syslogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsystemlog.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsystemlog.logintime
     *
     * @mbggenerated
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsystemlog.logintype
     *
     * @mbggenerated
     */
    private String logintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsystemlog.loginip
     *
     * @mbggenerated
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsystemlog.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsystemlog.syslogid
     *
     * @return the value of tbsystemlog.syslogid
     *
     * @mbggenerated
     */
    public Long getSyslogid() {
        return syslogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsystemlog.syslogid
     *
     * @param syslogid the value for tbsystemlog.syslogid
     *
     * @mbggenerated
     */
    public void setSyslogid(Long syslogid) {
        this.syslogid = syslogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsystemlog.userid
     *
     * @return the value of tbsystemlog.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsystemlog.userid
     *
     * @param userid the value for tbsystemlog.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsystemlog.logintime
     *
     * @return the value of tbsystemlog.logintime
     *
     * @mbggenerated
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsystemlog.logintime
     *
     * @param logintime the value for tbsystemlog.logintime
     *
     * @mbggenerated
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsystemlog.logintype
     *
     * @return the value of tbsystemlog.logintype
     *
     * @mbggenerated
     */
    public String getLogintype() {
        return logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsystemlog.logintype
     *
     * @param logintype the value for tbsystemlog.logintype
     *
     * @mbggenerated
     */
    public void setLogintype(String logintype) {
        this.logintype = logintype == null ? null : logintype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsystemlog.loginip
     *
     * @return the value of tbsystemlog.loginip
     *
     * @mbggenerated
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsystemlog.loginip
     *
     * @param loginip the value for tbsystemlog.loginip
     *
     * @mbggenerated
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsystemlog.createdate
     *
     * @return the value of tbsystemlog.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsystemlog.createdate
     *
     * @param createdate the value for tbsystemlog.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}