package com.hsjc.central.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * @author : zga
 * @date : 2015-12-2
 */
public class TbEmailSend implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.Subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.SendFlag
     *
     * @mbggenerated
     */
    private Boolean sendflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.SendTime
     *
     * @mbggenerated
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.byModule
     *
     * @mbggenerated
     */
    private String bymodule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.RequestKeyID
     *
     * @mbggenerated
     */
    private Long requestkeyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbemailsend.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.ID
     *
     * @return the value of tbemailsend.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.ID
     *
     * @param id the value for tbemailsend.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.Email
     *
     * @return the value of tbemailsend.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.Email
     *
     * @param email the value for tbemailsend.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.Subject
     *
     * @return the value of tbemailsend.Subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.Subject
     *
     * @param subject the value for tbemailsend.Subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.SendFlag
     *
     * @return the value of tbemailsend.SendFlag
     *
     * @mbggenerated
     */
    public Boolean getSendflag() {
        return sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.SendFlag
     *
     * @param sendflag the value for tbemailsend.SendFlag
     *
     * @mbggenerated
     */
    public void setSendflag(Boolean sendflag) {
        this.sendflag = sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.SendTime
     *
     * @return the value of tbemailsend.SendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.SendTime
     *
     * @param sendtime the value for tbemailsend.SendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.byModule
     *
     * @return the value of tbemailsend.byModule
     *
     * @mbggenerated
     */
    public String getBymodule() {
        return bymodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.byModule
     *
     * @param bymodule the value for tbemailsend.byModule
     *
     * @mbggenerated
     */
    public void setBymodule(String bymodule) {
        this.bymodule = bymodule == null ? null : bymodule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.RequestKeyID
     *
     * @return the value of tbemailsend.RequestKeyID
     *
     * @mbggenerated
     */
    public Long getRequestkeyid() {
        return requestkeyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.RequestKeyID
     *
     * @param requestkeyid the value for tbemailsend.RequestKeyID
     *
     * @mbggenerated
     */
    public void setRequestkeyid(Long requestkeyid) {
        this.requestkeyid = requestkeyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbemailsend.Content
     *
     * @return the value of tbemailsend.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbemailsend.Content
     *
     * @param content the value for tbemailsend.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}