package com.hsjc.central.domain;

import java.io.Serializable;
import java.util.Date;

public class TbSmsSend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.PhoneNum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.MsgContent
     *
     * @mbggenerated
     */
    private String msgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.SendFlag
     *
     * @mbggenerated
     */
    private Integer sendflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.SendTime
     *
     * @mbggenerated
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.byModule
     *
     * @mbggenerated
     */
    private String bymodule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsmssend.RequestKeyID
     *
     * @mbggenerated
     */
    private Long requestkeyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.ID
     *
     * @return the value of tbsmssend.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.ID
     *
     * @param id the value for tbsmssend.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.PhoneNum
     *
     * @return the value of tbsmssend.PhoneNum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.PhoneNum
     *
     * @param phonenum the value for tbsmssend.PhoneNum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.MsgContent
     *
     * @return the value of tbsmssend.MsgContent
     *
     * @mbggenerated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.MsgContent
     *
     * @param msgcontent the value for tbsmssend.MsgContent
     *
     * @mbggenerated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.SendFlag
     *
     * @return the value of tbsmssend.SendFlag
     *
     * @mbggenerated
     */
    public Integer getSendflag() {
        return sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.SendFlag
     *
     * @param sendflag the value for tbsmssend.SendFlag
     *
     * @mbggenerated
     */
    public void setSendflag(Integer sendflag) {
        this.sendflag = sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.SendTime
     *
     * @return the value of tbsmssend.SendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.SendTime
     *
     * @param sendtime the value for tbsmssend.SendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.byModule
     *
     * @return the value of tbsmssend.byModule
     *
     * @mbggenerated
     */
    public String getBymodule() {
        return bymodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.byModule
     *
     * @param bymodule the value for tbsmssend.byModule
     *
     * @mbggenerated
     */
    public void setBymodule(String bymodule) {
        this.bymodule = bymodule == null ? null : bymodule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmssend.RequestKeyID
     *
     * @return the value of tbsmssend.RequestKeyID
     *
     * @mbggenerated
     */
    public Long getRequestkeyid() {
        return requestkeyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmssend.RequestKeyID
     *
     * @param requestkeyid the value for tbsmssend.RequestKeyID
     *
     * @mbggenerated
     */
    public void setRequestkeyid(Long requestkeyid) {
        this.requestkeyid = requestkeyid;
    }
}