package com.hsjc.central.domain;

public class ThirdClients {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.client_id
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.client_secret
     *
     * @mbggenerated
     */
    private String clientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.contactorName
     *
     * @mbggenerated
     */
    private String contactorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.contactorPhone
     *
     * @mbggenerated
     */
    private String contactorphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.briefName
     *
     * @mbggenerated
     */
    private String briefname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.sso_password
     *
     * @mbggenerated
     */
    private String ssoPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb3rdclients.3rd_password
     *
     * @mbggenerated
     */
    private String 3rdPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.id
     *
     * @return the value of tb3rdclients.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.id
     *
     * @param id the value for tb3rdclients.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.client_id
     *
     * @return the value of tb3rdclients.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.client_id
     *
     * @param clientId the value for tb3rdclients.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.client_secret
     *
     * @return the value of tb3rdclients.client_secret
     *
     * @mbggenerated
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.client_secret
     *
     * @param clientSecret the value for tb3rdclients.client_secret
     *
     * @mbggenerated
     */
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret == null ? null : clientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.contactorName
     *
     * @return the value of tb3rdclients.contactorName
     *
     * @mbggenerated
     */
    public String getContactorname() {
        return contactorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.contactorName
     *
     * @param contactorname the value for tb3rdclients.contactorName
     *
     * @mbggenerated
     */
    public void setContactorname(String contactorname) {
        this.contactorname = contactorname == null ? null : contactorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.contactorPhone
     *
     * @return the value of tb3rdclients.contactorPhone
     *
     * @mbggenerated
     */
    public String getContactorphone() {
        return contactorphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.contactorPhone
     *
     * @param contactorphone the value for tb3rdclients.contactorPhone
     *
     * @mbggenerated
     */
    public void setContactorphone(String contactorphone) {
        this.contactorphone = contactorphone == null ? null : contactorphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.briefName
     *
     * @return the value of tb3rdclients.briefName
     *
     * @mbggenerated
     */
    public String getBriefname() {
        return briefname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.briefName
     *
     * @param briefname the value for tb3rdclients.briefName
     *
     * @mbggenerated
     */
    public void setBriefname(String briefname) {
        this.briefname = briefname == null ? null : briefname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.sso_password
     *
     * @return the value of tb3rdclients.sso_password
     *
     * @mbggenerated
     */
    public String getSsoPassword() {
        return ssoPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.sso_password
     *
     * @param ssoPassword the value for tb3rdclients.sso_password
     *
     * @mbggenerated
     */
    public void setSsoPassword(String ssoPassword) {
        this.ssoPassword = ssoPassword == null ? null : ssoPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb3rdclients.3rd_password
     *
     * @return the value of tb3rdclients.3rd_password
     *
     * @mbggenerated
     */
    public String get3rdPassword() {
        return 3rdPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb3rdclients.3rd_password
     *
     * @param 3rdPassword the value for tb3rdclients.3rd_password
     *
     * @mbggenerated
     */
    public void set3rdPassword(String 3rdPassword) {
        this.3rdPassword = 3rdPassword == null ? null : 3rdPassword.trim();
    }
}